// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.36.1
// source: remote.proto

package remotedesktop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RemoteDesktop_RegisterClient_FullMethodName      = "/remotedesktop.RemoteDesktop/RegisterClient"
	RemoteDesktop_AuthenticateControl_FullMethodName = "/remotedesktop.RemoteDesktop/AuthenticateControl"
	RemoteDesktop_HostStream_FullMethodName          = "/remotedesktop.RemoteDesktop/HostStream"
	RemoteDesktop_ControlStream_FullMethodName       = "/remotedesktop.RemoteDesktop/ControlStream"
)

// RemoteDesktopClient is the client API for RemoteDesktop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteDesktopClient interface {
	// Register client agent host
	RegisterClient(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Authenticate operator control client by Target Client ID
	AuthenticateControl(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Stream channel for Host Agent (Client): Host sends HostMessage (frames), receives ControlMessage (input)
	HostStream(ctx context.Context, opts ...grpc.CallOption) (RemoteDesktop_HostStreamClient, error)
	// Stream channel for Control Viewer: Control sends ControlMessage (input), receives HostMessage (frames)
	ControlStream(ctx context.Context, opts ...grpc.CallOption) (RemoteDesktop_ControlStreamClient, error)
}

type remoteDesktopClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteDesktopClient(cc grpc.ClientConnInterface) RemoteDesktopClient {
	return &remoteDesktopClient{cc}
}

func (c *remoteDesktopClient) RegisterClient(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, RemoteDesktop_RegisterClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteDesktopClient) AuthenticateControl(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, RemoteDesktop_AuthenticateControl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteDesktopClient) HostStream(ctx context.Context, opts ...grpc.CallOption) (RemoteDesktop_HostStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &RemoteDesktop_ServiceDesc.Streams[0], RemoteDesktop_HostStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteDesktopHostStreamClient{stream}
	return x, nil
}

type RemoteDesktop_HostStreamClient interface {
	Send(*HostMessage) error
	Recv() (*ControlMessage, error)
	grpc.ClientStream
}

type remoteDesktopHostStreamClient struct {
	grpc.ClientStream
}

func (x *remoteDesktopHostStreamClient) Send(m *HostMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remoteDesktopHostStreamClient) Recv() (*ControlMessage, error) {
	m := new(ControlMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *remoteDesktopClient) ControlStream(ctx context.Context, opts ...grpc.CallOption) (RemoteDesktop_ControlStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &RemoteDesktop_ServiceDesc.Streams[1], RemoteDesktop_ControlStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteDesktopControlStreamClient{stream}
	return x, nil
}

type RemoteDesktop_ControlStreamClient interface {
	Send(*ControlMessage) error
	Recv() (*HostMessage, error)
	grpc.ClientStream
}

type remoteDesktopControlStreamClient struct {
	grpc.ClientStream
}

func (x *remoteDesktopControlStreamClient) Send(m *ControlMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remoteDesktopControlStreamClient) Recv() (*HostMessage, error) {
	m := new(HostMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RemoteDesktopServer is the server API for RemoteDesktop service.
// All implementations must embed UnimplementedRemoteDesktopServer
// for forward compatibility
type RemoteDesktopServer interface {
	// Register client agent host
	RegisterClient(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Authenticate operator control client by Target Client ID
	AuthenticateControl(context.Context, *AuthRequest) (*AuthResponse, error)
	// Stream channel for Host Agent (Client): Host sends HostMessage (frames), receives ControlMessage (input)
	HostStream(RemoteDesktop_HostStreamServer) error
	// Stream channel for Control Viewer: Control sends ControlMessage (input), receives HostMessage (frames)
	ControlStream(RemoteDesktop_ControlStreamServer) error
	mustEmbedUnimplementedRemoteDesktopServer()
}

// UnimplementedRemoteDesktopServer must be embedded to have forward compatible implementations.
type UnimplementedRemoteDesktopServer struct {
}

func (UnimplementedRemoteDesktopServer) RegisterClient(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedRemoteDesktopServer) AuthenticateControl(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateControl not implemented")
}
func (UnimplementedRemoteDesktopServer) HostStream(RemoteDesktop_HostStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method HostStream not implemented")
}
func (UnimplementedRemoteDesktopServer) ControlStream(RemoteDesktop_ControlStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ControlStream not implemented")
}
func (UnimplementedRemoteDesktopServer) mustEmbedUnimplementedRemoteDesktopServer() {}

// UnsafeRemoteDesktopServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteDesktopServer will
// result in compilation errors.
type UnsafeRemoteDesktopServer interface {
	mustEmbedUnimplementedRemoteDesktopServer()
}

func RegisterRemoteDesktopServer(s grpc.ServiceRegistrar, srv RemoteDesktopServer) {
	s.RegisterService(&RemoteDesktop_ServiceDesc, srv)
}

func _RemoteDesktop_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDesktopServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteDesktop_RegisterClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDesktopServer).RegisterClient(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteDesktop_AuthenticateControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDesktopServer).AuthenticateControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteDesktop_AuthenticateControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDesktopServer).AuthenticateControl(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteDesktop_HostStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteDesktopServer).HostStream(&remoteDesktopHostStreamServer{stream})
}

type RemoteDesktop_HostStreamServer interface {
	Send(*ControlMessage) error
	Recv() (*HostMessage, error)
	grpc.ServerStream
}

type remoteDesktopHostStreamServer struct {
	grpc.ServerStream
}

func (x *remoteDesktopHostStreamServer) Send(m *ControlMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remoteDesktopHostStreamServer) Recv() (*HostMessage, error) {
	m := new(HostMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RemoteDesktop_ControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteDesktopServer).ControlStream(&remoteDesktopControlStreamServer{stream})
}

type RemoteDesktop_ControlStreamServer interface {
	Send(*HostMessage) error
	Recv() (*ControlMessage, error)
	grpc.ServerStream
}

type remoteDesktopControlStreamServer struct {
	grpc.ServerStream
}

func (x *remoteDesktopControlStreamServer) Send(m *HostMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remoteDesktopControlStreamServer) Recv() (*ControlMessage, error) {
	m := new(ControlMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RemoteDesktop_ServiceDesc is the grpc.ServiceDesc for RemoteDesktop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteDesktop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remotedesktop.RemoteDesktop",
	HandlerType: (*RemoteDesktopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterClient",
			Handler:    _RemoteDesktop_RegisterClient_Handler,
		},
		{
			MethodName: "AuthenticateControl",
			Handler:    _RemoteDesktop_AuthenticateControl_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HostStream",
			Handler:       _RemoteDesktop_HostStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ControlStream",
			Handler:       _RemoteDesktop_ControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "remote.proto",
}
