// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.36.1
// source: proto/remote.proto

package remotedesktop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RemoteDesktop_RegisterClient_FullMethodName      = "/remotedesktop.RemoteDesktop/RegisterClient"
	RemoteDesktop_AuthenticateControl_FullMethodName = "/remotedesktop.RemoteDesktop/AuthenticateControl"
	RemoteDesktop_CheckUpdate_FullMethodName         = "/remotedesktop.RemoteDesktop/CheckUpdate"
)

// RemoteDesktopClient is the client API for RemoteDesktop service.
type RemoteDesktopClient interface {
	RegisterClient(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	AuthenticateControl(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	CheckUpdate(ctx context.Context, in *UpdateCheckRequest, opts ...grpc.CallOption) (*UpdateCheckResponse, error)
}

type remoteDesktopClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteDesktopClient(cc grpc.ClientConnInterface) RemoteDesktopClient {
	return &remoteDesktopClient{cc}
}

func (c *remoteDesktopClient) RegisterClient(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, RemoteDesktop_RegisterClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteDesktopClient) AuthenticateControl(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, RemoteDesktop_AuthenticateControl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteDesktopClient) CheckUpdate(ctx context.Context, in *UpdateCheckRequest, opts ...grpc.CallOption) (*UpdateCheckResponse, error) {
	out := new(UpdateCheckResponse)
	err := c.cc.Invoke(ctx, RemoteDesktop_CheckUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteDesktopServer is the server API for RemoteDesktop service.
type RemoteDesktopServer interface {
	RegisterClient(context.Context, *RegisterRequest) (*RegisterResponse, error)
	AuthenticateControl(context.Context, *AuthRequest) (*AuthResponse, error)
	CheckUpdate(context.Context, *UpdateCheckRequest) (*UpdateCheckResponse, error)
	mustEmbedUnimplementedRemoteDesktopServer()
}

// UnimplementedRemoteDesktopServer must be embedded to have forward compatible implementations.
type UnimplementedRemoteDesktopServer struct {
}

func (UnimplementedRemoteDesktopServer) RegisterClient(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedRemoteDesktopServer) AuthenticateControl(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateControl not implemented")
}
func (UnimplementedRemoteDesktopServer) CheckUpdate(context.Context, *UpdateCheckRequest) (*UpdateCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUpdate not implemented")
}
func (UnimplementedRemoteDesktopServer) mustEmbedUnimplementedRemoteDesktopServer() {}

// UnsafeRemoteDesktopServer may be embedded to opt out of forward compatibility for this service.
type UnsafeRemoteDesktopServer interface {
	mustEmbedUnimplementedRemoteDesktopServer()
}

func RegisterRemoteDesktopServer(s grpc.ServiceRegistrar, srv RemoteDesktopServer) {
	s.RegisterService(&RemoteDesktop_ServiceDesc, srv)
}

func _RemoteDesktop_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDesktopServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteDesktop_RegisterClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDesktopServer).RegisterClient(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteDesktop_AuthenticateControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDesktopServer).AuthenticateControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteDesktop_AuthenticateControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDesktopServer).AuthenticateControl(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteDesktop_CheckUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDesktopServer).CheckUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteDesktop_CheckUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDesktopServer).CheckUpdate(ctx, req.(*UpdateCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteDesktop_ServiceDesc is the grpc.ServiceDesc for RemoteDesktop service.
var RemoteDesktop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remotedesktop.RemoteDesktop",
	HandlerType: (*RemoteDesktopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterClient",
			Handler:    _RemoteDesktop_RegisterClient_Handler,
		},
		{
			MethodName: "AuthenticateControl",
			Handler:    _RemoteDesktop_AuthenticateControl_Handler,
		},
		{
			MethodName: "CheckUpdate",
			Handler:    _RemoteDesktop_CheckUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/remote.proto",
}
